#!/usr/bin/env python3
"""Build src/spur_table.h: the Nikkaluokta -> Kebnekaise -> Singi approach.

Inputs (already in data/, produced from the source GPX + OSM + EU-DEM):
  - data/nikka_keb_track_ele.json   Topo GPS track 54676.gpx (Peter Risberg),
                                    thinned to 25 m, elevations replaced with
                                    EU-DEM (the recorded ele was too noisy:
                                    1697 m raw ascent vs 324 m terrain truth)
  - data/keb_singi_track_ele.json   OSM "Kungsleden Etapp 9" ways + EU-DEM

Travel order is Nikkaluokta (index 0) -> Singi, matching a southbound hike.
Cumulative ascent/descent computed at full resolution (3 m dead-band) before
Douglas-Peucker simplification, same as the main route.

    python tools/build_spur.py > src/spur_table.h
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from gpx_to_route import haversine, douglas_peucker_idx, cum_climb

KEB = (67.8671, 18.6194)
NIKKA = (67.8508353, 19.0137288)
SINGI = (67.8504, 18.316)
EPS_M = 150.0


def load(name, start_near):
    here = os.path.dirname(__file__)
    t = [tuple(p) for p in json.load(open(os.path.join(here, "..", "data", name)))]
    if haversine(t[0][:2], start_near) > haversine(t[-1][:2], start_near):
        t = t[::-1]
    return t


def main():
    user = load("nikka_keb_track_ele.json", NIKKA)   # Nikkaluokta -> Kebnekaise
    osm = load("keb_singi_track_ele.json", KEB)      # Kebnekaise -> Singi
    assert haversine(user[0][:2], NIKKA) < 500
    assert haversine(osm[-1][:2], SINGI) < 500

    joint = haversine(user[-1][:2], osm[0][:2])
    print(f"// joint gap at Kebnekaise: {joint:.0f} m", file=sys.stderr)
    track = user + osm

    asc_full, desc_full = cum_climb(track, deadband=3.0)
    idxs = douglas_peucker_idx(track, EPS_M)
    simp = [track[i] for i in idxs]
    cumA = [asc_full[i] for i in idxs]
    cumD = [desc_full[i] for i in idxs]

    cum = [0.0]
    for i in range(1, len(simp)):
        cum.append(cum[-1] + haversine(simp[i - 1][:2], simp[i][:2]))

    keb_i = min(range(len(simp)), key=lambda i: haversine(simp[i][:2], KEB))

    print("// Generated by build_spur.py — Nikkaluokta -> Kebnekaise -> Singi")
    print("// Sources: Topo GPS track 54676 (geometry) + OSM Etapp 9 + EU-DEM (elevation)")
    print("#pragma once")
    print('#include "geo.h"')
    print("static const RoutePoint SPUR_ROUTE[] = {")
    for (lat, lon, ele), c, ca, cd in zip(simp, cum, cumA, cumD):
        print(f"  {{{lat:.6f}f, {lon:.6f}f, {c:.1f}f, {ele:.1f}f, {ca:.1f}f, {cd:.1f}f}},")
    print("};")
    print(f"static const int SPUR_N = {len(simp)};")
    print(f"static const int SPUR_KEB_IDX = {keb_i};   // Kebnekaise Fjällstation")
    print(f"// total {cum[-1]/1000:.1f} km, ascent {cumA[-1]:.0f} m, descent {cumD[-1]:.0f} m",
          file=sys.stderr)


if __name__ == "__main__":
    main()
